# Generated by Django 6.1 on 2026-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_department', models.CharField(max_length=50)),
                ('student_semester', models.IntegerField()),
                ('student_phone', models.IntegerField()),
            ],
        ),
    ]
