# Generated by Django 6.1 on 2026-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
