from django.shortcuts import render

# Create your views here.
def index(request):
    students = [
        {
            'id': 1,
            'name': 'Rahim',
            'age': 20,
            'city': 'Dhaka',
            'department': 'CSE',
            'semester': 5,
            'email': 'rahim@gmail.com',
            'phone': '01711111111',
            'gpa': 3.75,
            'status': 'Active',
        },
        {
            'id': 2,
            'name': 'Karim',
            'age': 21,
            'city': 'Rajshahi',
            'department': 'EEE',
            'semester': 6,
            'email': 'karim@gmail.com',
            'phone': '01722222222',
            'gpa': 3.60,
            'status': 'Active',
        },
        {
            'id': 3,
            'name': 'Sakib',
            'age': 22,
            'city': 'Chittagong',
            'department': 'CSE',
            'semester': 7,
            'email': 'sakib@gmail.com',
            'phone': '01733333333',
            'gpa': 3.80,
            'status': 'Active',
        },
        {
            'id': 4,
            'name': 'Hasan',
            'age': 20,
            'city': 'Sylhet',
            'department': 'BBA',
            'semester': 4,
            'email': 'hasan@gmail.com',
            'phone': '01744444444',
            'gpa': 3.50,
            'status': 'Inactive',
        },
        {
            'id': 5,
            'name': 'Nayeem',
            'age': 23,
            'city': 'Khulna',
            'department': 'CSE',
            'semester': 8,
            'email': 'nayeem@gmail.com',
            'phone': '01755555555',
            'gpa': 3.90,
            'status': 'Active',
        },
        {
            'id': 6,
            'name': 'Fahim',
            'age': 21,
            'city': 'Rangpur',
            'department': 'EEE',
            'semester': 6,
            'email': 'fahim@gmail.com',
            'phone': '01766666666',
            'gpa': 3.45,
            'status': 'Active',
        },
        {
            'id': 7,
            'name': 'Shuvo',
            'age': 22,
            'city': 'Barisal',
            'department': 'BBA',
            'semester': 7,
            'email': 'shuvo@gmail.com',
            'phone': '01777777777',
            'gpa': 3.70,
            'status': 'Active',
        },
        {
            'id': 8,
            'name': 'Rifat',
            'age': 20,
            'city': 'Mymensingh',
            'department': 'CSE',
            'semester': 5,
            'email': 'rifat@gmail.com',
            'phone': '01788888888',
            'gpa': 3.55,
            'status': 'Inactive',
        },
        {
            'id': 9,
            'name': 'Tanvir',
            'age': 23,
            'city': 'Comilla',
            'department': 'EEE',
            'semester': 8,
            'email': 'tanvir@gmail.com',
            'phone': '01799999999',
            'gpa': 3.85,
            'status': 'Active',
        },
        {
            'id': 10,
            'name': 'Arif',
            'age': 21,
            'city': 'Gazipur',
            'department': 'CSE',
            'semester': 6,
            'email': 'arif@gmail.com',
            'phone': '01811111111',
            'gpa': 3.65,
            'status': 'Active',
        },
    ]
     
    products = {
    'shirt': 'Formal Shirt',
    'pant': 'Jeans Pant',
    'tShirt': 'T-Shirt',
    'panjabi': 'Panjabi',
    'jacket': 'Denim Jacket',
    'sweater': 'Sweater',
    'hoodie': 'Hoodie',
    'shorts': 'Shorts',
    }
    return render(
        request,
        'styles/index.html',
        {
            'products': products,
            'students': students
        }
    )
def bootStrap(request):
    return render(
        request,
        'bootStrap/index.html',
    )
def tailwind(request):
    return render(
        request,
        'tailwind/tailwind.html',
    )